package com.eventusplus.audit.model;

public enum AuditAction {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_UPDATED,
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    REGISTRATION_CREATED,
    CHECK_IN_CONFIRMED,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED
}
